print ("----primer 1 (forword)----")
gc1 = int(input("enter the number of gc:"))
at1 = int(input("the number of at:"))
tm1 = 4 * (gc1) + 2 * (at1)
print ("tm for primer 1 is :" , tm1)
print ("----primer 2 (reverse)----")
gc2 = int(input("enter the number of gc:"))
at2 = int(input("the number of at:"))
tm2 = 4 * (gc2) + 2 * (at2)
print ("tm for primer 2 is :" , tm2)
diff = abs(tm1 - tm2)
print ("the difference :" , diff)